environments:
  dev:
    url: http://localhost:8080
  product:
    url: http://localhost:8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://43.201.144.113:3306/mkc
    username: root
    password: 6548

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mkc
#    username: root
#    password: taeyun1215

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghkwon0130@gmail.com
    password: uglzohnwrzkqwfzb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  redis:
    port: 6379
    host: 127.0.0.1
    username: root
    password: 3iZXb4AK5dH5

file:
  upload:
    path: ~/yeh/images
# todo : aws s3 버켓에 추가하기
# todo : cloudflare 라이브러리 다운 받고 추가하기