environments:
  dev:
    url: https://www.devyeh.com
  product:
    url: https://www.devyeh.com

server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/test
#    username: root
    username: guhyeon
#    password: 6548
    password: Ps$k0O^IA7pM

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mkc
#    username: root
#    password: taeyun1215

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghkwon0130@gmail.com
    password: vgknsdygxeinluwt
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  redis:
    port: 6379
    host: 39.117.201.199
    username: root
    password: 3iZXb4AK5dH5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

cloud:
  aws:
    credentials:
      access-key: AKIA5G5YMWOQTZQHBMFJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: yeh-bucket
    stack:
      auto: false

#cloud:
#  aws:
#    credentials:
#      access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
#      secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
#    region:
#      static: ap-northeast-2
#    s3:
#      bucket: ${{ secrets.AWS_S3_BUCKET }}
#    stack:
#      auto: false

property:
  secretKey: pvxmdnogszqqakzssfvvivldk
  tokenExpiresTime: 60
  refreshTokenExpiresTime: 120