environments:
  dev:
    url: http://localhost:8080
  product:
    url: http://localhost:8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/mkc
    username: root
    password: taeyun1215

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://193.123.230.252:3306/mkc
#    username: root
#    password: u7q2q8bvRZ7d

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghkwon0130@gmail.com
    password: zbptllrlqgohvsus
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  redis:
    port: 6379
    host: 127.0.0.1

file:
  upload:
    path: C:/Users/tylee/Desktop/image/
# todo : aws s3 버켓에 추가하기
# todo : cloudflare 라이브러리 다운 받고 추가하기